[package]
name = "uwugc"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator-api2 = "0.2.21"
bounded-vec-deque = "0.1.1"
crossbeam-utils = "0.8.21"
parking_lot = { path = "../parking_lot" }
portable-atomic = "1.10.0"
sealed = "0.6.0"
